################################################################################
cli-wallet-full:
  restart: always
  image: denkhaus/bitshares-2:$TAG_FULL  
  ports:
    - "127.0.0.1:8095:8095"
  volumes:
    - /var/docker/bts/data:/data
  command: "/bitshares/programs/cli_wallet/cli_wallet -s wss://bitshares.openledger.info/ws -H 0.0.0.0:8095 -d"

################################################################################
cli-wallet-test:
  restart: always
  image: denkhaus/bitshares-2:$TAG_TEST
  ports:
    - "127.0.0.1:8094:8094"
  volumes:
    - /var/docker/bts/testdata:/data
  command: "/bitshares/programs/cli_wallet/cli_wallet --chain-id 39f5e2ede1f8bc1a3a54a7914414e3779e33193f1f5693510e73cb7a87617447 -s wss://node.testnet.bitshares.eu/ws -H 0.0.0.0:8094 -d"  